

CREATE TABLE `courses` ( 
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT , 
	`name` VARCHAR(255) NOT NULL , 
	`description` TEXT NOT NULL , 
	`period` TINYINT UNSIGNED NOT NULL , 
	`price_month` DECIMAL(6,2) UNSIGNED NOT NULL , 
	`price_full` DECIMAL(6,2) UNSIGNED NOT NULL , 
	`author` INT(11) UNSIGNED NOT NULL , 
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	`active` TINYINT(1) NOT NULL DEFAULT '0' , 
	PRIMARY KEY (`id`)
) ENGINE = InnoDB;