CREATE TABLE `review` ( 
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT , 
	`group_id` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
	`lecture_id` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
	`user` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
	`video_url` VARCHAR(255) NOT NULL , 
	`video_url_mp4` TEXT NULL , 
	`video_url_webm` TEXT NULL , 
	`text` TEXT NOT NULL , 
	`score` TINYINT(3) UNSIGNED NOT NULL , 
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;