CREATE TABLE `news` ( 
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT , 
	`title` VARCHAR(255) NOT NULL , 
	`text` TEXT NOT NULL , 
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	`active` BOOLEAN NOT NULL DEFAULT TRUE , 
	PRIMARY KEY (`id`)
) ENGINE = InnoDB;

ALTER TABLE `review` ADD `item_is_viewed` TINYINT UNSIGNED NOT NULL DEFAULT '0' AFTER `ts`;